# Generated by Django 5.2.6 on 2025-10-08 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=16, unique=True, verbose_name='员工名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('position', models.SmallIntegerField(choices=[(1, '销售员'), (2, '经理'), (3, '会计'), (4, '采购员'), (5, '技术员'), (6, '售后'), (7, '其他')], default=1, verbose_name='部门')),
            ],
            options={
                'db_table': 'employee_info',
            },
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=32, verbose_name='商家名称')),
                ('phone', models.CharField(max_length=16, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系邮箱')),
                ('address', models.CharField(max_length=255, verbose_name='联系地址')),
            ],
            options={
                'db_table': 'merchant_info',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='商品名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品描述')),
                ('catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='MerchantItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货价')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.merchantinfo')),
                ('merchant_items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.purchaseitems')),
            ],
            options={
                'db_table': 'merchant_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='销售价')),
                ('Inventory_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('items_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.purchaseitems')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='进货数量')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.employeeinfo')),
                ('merchant_items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.merchantitems')),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='SellOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_date', models.TimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, '未完成'), (2, '已完成'), (3, '已取消')], default=1, verbose_name='状态')),
                ('inventory_items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.inventoryitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OnlineShop.userinfo')),
            ],
            options={
                'db_table': 'sell_orders',
            },
        ),
    ]
