# Generated by Django 5.2.6 on 2025-10-11 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待入库'), (2, '已入库'), (3, '已取消')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='position',
            field=models.SmallIntegerField(choices=[(1, '销售员'), (2, '经理'), (3, '会计'), (4, '采购员'), (5, '技术员'), (6, '售后'), (7, '其他')], default=1, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShop.purchaseitems'),
        ),
        migrations.AlterField(
            model_name='merchantitems',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShop.merchantinfo'),
        ),
        migrations.AlterField(
            model_name='merchantitems',
            name='merchant_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShop.purchaseitems'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.employeeinfo'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='merchant_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.merchantitems'),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='inventory_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.inventoryitems'),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.userinfo'),
        ),
    ]
