# Generated by Django 5.2.6 on 2025-10-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0002_purchaseorders_created_at_purchaseorders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantitems',
            name='merchant_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_items_set', to='OnlineShop.purchaseitems'),
        ),
    ]
