# Generated by Django 5.2.6 on 2025-10-13 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0003_alter_merchantitems_merchant_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入职日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='position',
            field=models.SmallIntegerField(choices=[(1, '销售员'), (2, '经理'), (3, '会计'), (4, '采购员'), (5, '技术员'), (6, '售后'), (7, '仓库管理员'), (8, '其他')], default=1, verbose_name='职位'),
        ),
    ]
