# Generated by Django 5.2.6 on 2025-10-06 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0003_remove_userinfo_nickname_userinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='inventoryitems',
            name='ask_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitems',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='inventoryitems',
            name='inventory_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='merchantinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='merchantinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='employeename',
            field=models.CharField(default='employee', max_length=16, unique=True, verbose_name='员工名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='F', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='phone',
            field=models.CharField(default=111, max_length=20, verbose_name='电话号码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='items_name',
            field=models.CharField(default=1, max_length=100, verbose_name='商品名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantinfo',
            name='merchant_name',
            field=models.CharField(default=1, max_length=32, verbose_name='商家名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='position',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='merchantinfo',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='Inventory_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量'),
            preserve_default=False,
        ),
    ]
