# Generated by Django 5.2.6 on 2025-10-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0004_remove_employeeinfo_name_remove_employeeinfo_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorders',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
