# Generated by Django 5.2.6 on 2025-10-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0004_employeeinfo_date_sellorders_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorders',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
