# Generated by Django 5.2.6 on 2025-10-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0005_sellorders_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShop.purchaseitems', verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='merchantitems',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShop.merchantinfo', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='merchantitems',
            name='merchant_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_items_set', to='OnlineShop.purchaseitems', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.employeeinfo', verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='merchant_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.merchantitems', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='inventory_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.inventoryitems', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShop.userinfo', verbose_name='用户'),
        ),
    ]
