# Generated by Django 5.2.6 on 2025-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0006_alter_inventoryitems_items_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='Inventory_quantity',
            new_name='inventory_quantity',
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='order_quantity',
            field=models.IntegerField(verbose_name='购买数量'),
        ),
    ]
